language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
  - CXXFLAGS="-Werror"
sudo: required
dist: trusty
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq && sudo apt-get install -qqy automake libcppunit-dev valgrind r-base-core; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew tap homebrew/science && brew install cppunit valgrind r gawk; fi
before_script:
  - ./bootstrap
script:
  - make unittests
  - make scrm scrm_dbg && ./tests/test_binaries.sh
  - make algorithmtest
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./tests/testScrmWithMs.sh; fi
before_deploy:
  - ./.travis/build_src_pkg.sh
  - ./.travis/build_static_binaries.sh
  - ./.travis/build_win_binaries.sh
deploy:
  provider: releases
  api_key:
    secure: UrEhKzTdSr7NB4ptDYcWKN02XjfgJgN1fNFu8G2a52Jpk1Z3UeenbmKxIDLj11JUlU427br7t1oQyScYSYEGEM5VEI0aWf7D2i9cPfSRD9QYnHOPG2XZE/xgkwWAm0s4TjnTBmudGSxs9g2KRjDXLz1f191jVGIghnHlxw/C9Ok=
  file:
    - "scrm-src.tar.gz"
    - "scrm-x64-static.tar.gz"
    - "scrm-win32.zip"
    - "scrm-win64.zip"
  on:
    tags: true
    condition: "$CC = gcc"
    condition: "$TRAVIS_OS_NAME == linux"
